### ISSUE TITLE
json_object does not work as documented

### ISSUE THREAD

**Issue by bjoernhaeuser** [mysqludf/lib_mysqludf_json#1]
Hey,

I just installed the current master and trying to use json_object:

``` sql
create table foo (id integer(11) primary key auto_increment, bar varchar(255) not null);

INSERT INTO foo (bar) VALUES ('foo');
INSERT INTO foo (bar) VALUES ('bar');

SELECT json_object(id, bar) FROM foo;
```

I thought that this should provide the right structure, but I am getting this error:
ERROR 1123 (HY000): Can't initialize function 'json_object'; Invalid json member name - name cannot be empty

Thanks in advance
Björn

P.S.: 

``` sql
SELECT VERSION();
+-----------+
| VERSION() |
+-----------+
| 5.5.30    |
+-----------+
```

**Comment by dm8tbr** [comment]
I worked around this issue by rewriting 

```
    json_object(id, bar) 
```

as 

```
    json_object(id AS 'id', bar AS 'bar').
```

Not pretty, but it works.

**Comment by jimbocoder** [comment]
This just bit me too, on 5.5.32.  Is it a version problem?

**Comment by bjoernhaeuser** [comment]
Don't know, but this repo does not like it's maintained. :-(
